version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - boilerplate-generator
      - webhook
    restart: always

  boilerplate-generator:
    build:
      context: .
      dockerfile: apps/boilerplate-generator/Dockerfile
    env_file: .env
    ports:
      - "4000:4000"
    restart: always

  webhook:
    build:
      context: .
      dockerfile: apps/webhook/Dockerfile
    env_file: .env
    ports:
      - "5000:5000"
    restart: always
