name: Deploy to EC2

on:
  push:
    branches: [master, main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Add EC2 to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        env:
          ENV_FILE_CONTENT: ${{ secrets.ENV_FILE_CONTENT }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          ssh -o ServerAliveInterval=30 $EC2_USER@$EC2_HOST << 'EOF'
            cd ~/Codehub
            git pull origin master

            # Write .env from secret
            echo "$ENV_FILE_CONTENT" > .env

            # Build and restart containers
            docker compose down
            docker compose build --no-cache
            docker compose up -d --remove-orphans
          EOF